sudo: false
dist: xenial
language: python
python:
  # General Python matrix
  - "3.5"
matrix:
  include:
    # Additional job that can also deploy to PyPI
    - python: "3.6"
      env: "PYPI_DEPLOY=true"
install:
  - "nvm install node"  # latest version of node
  - "nvm use node"
  - "npm install -g gulp-cli"
  - "npm install"
  - "pip install -e .[dev]"
script:
  - "gulp assets --env=deploy"
  - "make pytest"
env:
  global:
    - "PYPI_DEPLOY=false"
deploy:
  provider: pypi
  user: sqre-admin
  password:
    secure: "csXR1Hq18Omj7nWHXP9iq9N6DxjjOoXCB2S3YSi/cK4neKV/p7+yxqBkWyA8WXpw7lFtlL8Umm0kQGMTK9GAAQnaxCoPPai3ifoUhbmvLn+x1uMkiKL+v9qJtAyjCfzjrnawXKrgyIU/VkgTKJ9C81bPJWP8Qhw2bJFY2usRyOqd7l44opP/njymoaDNdn4a6kHvNin9+eTiJXFrcisihsbzZV5outypyxftx3AJYfNOOjtaMz+QtAk/RZumV3gBLOq74pWcUiA4G3c439JhmBbQ6nERnN7ssznA/nQzmj42pqD2YWt5+F/afA8okMG8oDbMj428Ifmp027R3MJwJ65GC0G84ciKVQW08pVQt6e+MleDDGHSwYEMYLkSXmBUYF9YmRTt4KnEczEgzuIuqbLTgxgueYRm6NdE5TGD4M8pMDnRXp2b/Zk3z3gboXeocG3hvIBakoTzJLKpLYLgO0RzhDqy8A74sEbe4iZj3CJwh5ilYb/NH6KZqe+Y3UAbuJvVjGT/n194Dw2Lkqz2md1M9Gr3/DhGALrx+WEmr7m3wGM5Cxluk8A3TcNu7o0LldlGSEkeeSO1HnHOgpsm2DQfvGybfw8Zb4wSlE+Gh7VfWu4fj68KxHpCTdKcYjTSrGCdJJI3T3FaKgZciguOTZYzn5mUl7tYBUrZDgSxly0="
  on:
    tags: true
    repo: "lsst-sqre/lander"
    condition: "$PYPI_DEPLOY = true"
  skip_upload_docs: true
  distributions: sdist bdist_wheel
  skip_cleanup: true
