name: CI

"on": [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # full history for setuptools_scm

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Read .nvmrc
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}

      - name: NPM install
        run: |
          npm install -g gulp-cli
          npm install

      - name: Python install
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
          pip install tox

      - name: Build assets
        run: gulp assets

      - name: Run tests
        run: tox -e py,lint,typing

  pypi:

    runs-on: ubuntu-latest
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # full history for setuptools_scm

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Read .nvmrc
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}

      - name: NPM install
        run: |
          npm install -g gulp-cli
          npm install

      - name: Python install
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
          pip install --upgrade setuptools wheel twine

      - name: Build assets
        run: gulp assets

      - name: Build and publish
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_SQRE_ADMIN }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
